services:
  db:
    restart: always
    image: "postgres:12.3-alpine"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    networks:
      - rengine_network
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - rengine_network

  celery:
    image: local/rengine-celery:v0.2
    restart: unless-stopped
    volumes:
      - ./web:/home/rengine/rengine
      # - ./data/reNgine/github_repos:/usr/src/github
      # - ./data/reNgine/wordlist:/usr/src/wordlist
      # - ./data/reNgine/scan_results:/usr/src/scan_results
      # - ./data/reNgine/gf_patterns:/root/.gf
      # - ./data/reNgine/nuclei_templates:/root/nuclei-templates
      # - ./data/reNgine/tool_config:/root/.config
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
      - MIN_CONCURRENCY=${MIN_CONCURRENCY}
    depends_on:
      - db
      - redis
    networks:
      - rengine_network

  celery-beat:
    image: local/rengine-celery:v0.2
    restart: unless-stopped
    entrypoint: /usr/src/app/beat-entrypoint.sh
    command: celery -A reNgine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./web:/home/rengine/rengine
      # - ./data/reNgine/github_repos:/usr/src/github
      # - ./data/reNgine/wordlist:/usr/src/wordlist
      # - ./data/reNgine/scan_results:/usr/src/scan_results
      # - ./data/reNgine/gf_patterns:/root/.gf
      # - ./data/reNgine/nuclei_templates:/root/nuclei-templates
      # - ./data/reNgine/tool_config:/root/.config
    networks:
      - rengine_network

  web:
    image: local/rengine-web:v0.2
    restart: unless-stopped
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      # THIS IS A MUST FOR CHECKING UPDATE, EVERYTIME A COMMIT IS MERGED INTO
      # MASTER, UPDATE THIS!!! MAJOR.MINOR.PATCH https://semver.org/
      - RENGINE_CURRENT_VERSION='2.0.5'
    volumes:
      - ./web:/home/rengine/app
      # - ./data/reNgine/github_repos:/usr/src/github
      # - ./data/reNgine/wordlist:/usr/src/wordlist
      # - ./data/reNgine/scan_results:/usr/src/scan_results
      # - ./data/reNgine/gf_patterns:/root/.gf
      # - ./data/reNgine/nuclei_templates:/root/nuclei-templates
      # - ./data/reNgine/tool_config:/root/.config
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - celery-beat
    networks:
      - rengine_network

networks:
  rengine_network:
