name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub's Container Registry
        run: echo "${{ secrets.CONTAINER_REGISTRY_SECRET }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build . -t ghcr.io/Security-Tools-Alliance/rengine-ng:latest

      - name: Push the Docker image
        run: docker push ghcr.io/Security-Tools-Alliance/rengine-ng:latest
