name: Close issues on PR merge to release branch

on:
  pull_request:
    types:
      - closed

jobs:
  close-related-issues:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Close linked issues
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.pull_request.body }}
          comment: "This issue is being closed because the related PR has been merged into a release branch."
